name: 'build flutter-pi'
description: 'Install build deps, clone, build and install flutter-pi'
inputs:
  image:
    description: 'The docker image to use for building.'
    required: true
  cmake-args:
    description: 'The additional args passed to cmake.'
    required: true
  install-gstreamer-video-player-deps:
    description: 'If true, install the dependencies required for building the gstreamer video player plugin.'
    required: false
    default: 'false'
  install-gstreamer-audio-player-deps:
    description: 'If true, install the dependencies required for building the gstreamer audio player plugin.'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
   - uses: actions/checkout@v2
     
   - uses: docker/setup-qemu-action@v2
     
   - name: Clone, Configure, Build and Install flutter-pi
     uses: docker://${{ inputs.image }}
     with:
       entrypoint: /bin/bash
       args: |
         -c "\
         export DEBIAN_FRONTEND=noninteractive && \
         echo "::group::Installing dependencies" && \
         apt-get update && \
         apt-get install -y git cmake ninja-build gcc g++ libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdrm-dev libgbm-dev fonts-liberation fontconfig libsystemd-dev libinput-dev libudev-dev libxkbcommon-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-plugins-bad gstreamer1.0-libav && \
         echo "::endgroup::" && \
         echo "::group::Cloning" && \
         git clone https://github.com/ardera/flutter-pi && \
         git checkout ${{ github.ref }} && \
         echo "::endgroup::" && \
         echo "::group::Configuring build" && \
         cmake -Bflutter-pi/build -Sflutter-pi -GNinja -DCMAKE_BUILD_TYPE=Release && \
         echo "::endgroup::" && \
         echo "::group::Building" && \
         ninja -Cflutter-pi/build && \
         echo "::endgroup::" && \
         echo "::group::Installing" && \
         ninja -Cflutter-pi/build install \
         "
